import './globals.css'
import type { Metadata } from 'next'
import {NavigationMenu} from '@components/Navigation/NavigationMenu';
import { Footer } from '@components/footer';
import {inter} from '@components/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden bg-gradient-to-r from-[#141959]/[.7] to-[#18d8d9]/[.7]  `}>
        <NavigationMenu/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
